
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_app_development

test:
  <<: *default
  database: task_app_test


production:
  <<: *default
  database: task_app_production
  username: task_app
  password: <%= ENV['task_app_DATABASE_PASSWORD'] %>
